examples/chess/src/chess_rs/Cargo.toml, examples/chess/src/chess_rs/lib.rs, examples/counter/src/counter_rs/Cargo.toml, examples/counter/src/counter_rs/lib.rs, examples/counter/src/inter2_rs/Cargo.toml, examples/counter/src/inter2_rs/lib.rs, examples/counter/src/inter_rs/Cargo.toml, examples/counter/src/inter_rs/lib.rs, examples/print/src/print_rs/Cargo.toml, examples/profile/src/profile_inter_rs/Cargo.toml, examples/profile/src/profile_rs/Cargo.toml, examples/profile/src/profile_rs/lib.rs, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-macros/src/export.rs, src/ic-cdk/Cargo.toml, src/ic-cdk/src/lib.rs
Export candid from `ic_cdk::candid`, and user projects are encouraged to use this alias for candid. This avoids problems when the candid version is different on the user project from the one used in CDK.
=> chore: remove candid crate from examples

src/ic-cdk-macros/Cargo.toml, src/ic-cdk-macros/src/export.rs, src/ic-cdk/src/api/stable.rs
It broke when they removed the export module from root, but we don't need it.
=> chore: set syn package's patch version

src/ic-cdk/src/api/call.rs, src/ic-cdk/src/futures.rs
This should save some cycles and some memory as we don't to allocate
more than we need anymore.
=> chore: use a reply std::io::write instead of serializing to a vector

src/ic-cdk-macros/Cargo.toml, src/ic-cdk/Cargo.toml
Update candid to 0.6.17 which supports more efficient serialization/de-serialization of `Vec<u8>`
=> chore: update candid to 0.6.17

src/ic-cdk/src/api.rs
This change adds minimalistic certification API based on the function
that were already exported in the ic0 module.
* set_certified_data can only be called from initialization
hooks/callbacks/update calls. It copies the data to the system for
subsequent certification that happens asynchronously.
* data_certificate can only be called from query calls. It requests a
certificate authenticating the previously set data from the system.
=> feat: expose canister certification API

src/ic-cdk/Cargo.toml, src/ic-cdk/src/lib.rs
The CDK is now BYOA. We'll need to publish this under a new minor version.
=> feat: remove wee_alloc as the global allocation in CDK

src/ic-cdk-macros/Cargo.toml, src/ic-cdk/Cargo.toml
Developers can opt-out candid/cdk feature with `default-features = false`
=> fix: provide a default feature for candid/cdk

src/ic-cdk/src/api.rs, src/ic-cdk/src/api/call.rs
WASM uses i32/i64 everywhere (it does not define unsigned integers), and
the spec is clear on this that it should be unsigned unless otherwise
specified. This PR matches the spec on the external API (still uses signed
integers for the ic0 module interface).
Fixes #66.
=> feat: use unsigned integers where they are unsigned in the spec

src/ic-cdk/src/api/call.rs
The previous implementation is not Send + Sync, which in WASM doesn't
matter but makes some libraries impossible to use. This "cheats" by
declaring our Rc<RefCell<>> cell as being Send + Sync in WASM, and have
a non-WASM implementation that uses regular Arc<Mutex<>>.
This is backward compatible, but technically should increment the minor
as the type traits impl changed. The CallFuture<> is now Send+Sync.
=> refactor: make a ref counted cell wasm implementation

src/ic-cdk-macros/Cargo.toml, src/ic-cdk/Cargo.toml
- bump candid to 0.7.1
- remove ic-types direct dependency
=> chore: release 0.3.1

src/ic-cdk-optimizer/Cargo.toml
beta.4 introduced errors like these:
error[E0658]: arbitrary expressions in key-value attributes are unstable
--> /Users/ericswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
|
8 | #![doc = include_str!("../README.md")]
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
error[E0658]: use of unstable library feature 'osstring_ascii'
--> /Users/ericswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/parse/matches/matched_arg.rs:130:19
|
130 |                 v.eq_ignore_ascii_case(val)
|                   ^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #70516 <https://github.com/rust-lang/rust/issues/70516> for more information
=> chore: ic-cdk-optimizer: pin to clap-3.0.0-beta.2

src/ic-cdk-macros/src/export.rs, src/ic-cdk-macros/src/lib.rs, src/ic-cdk/src/api/call.rs, src/ic-cdk/src/api/ic0.rs
This adds 2 new attributes 'heartbeat' and 'inspect_message' and also exposes 2 additional ic0 methods 'accept_message' and 'method_name' which are required when using 'inspect_message'.
=> feat: add support for 'heartbeat' and 'inspect_message'

src/ic-certified-map/CHANGELOG.md, src/ic-certified-map/src/rbtree.rs, src/ic-certified-map/src/rbtree/test.rs
This change implements key-value range queries for the certified map
and fixes the handling of key range queries.
Before this change, the key range queries always included key
neighbors into the witness, even if the actual key bound is present in
the tree.
For example, if the tree contains keys '0'..'9', key_range('1', '8')
would produce a witness with keys '0'..'9' instead of just '1'..'8'
with everything else pruned.
This made it hard/impossible to use this map in some applications,
e.g., for registry certification.
=> feat: implement proper range queries for certified map

.github/workflows/conventional-commits.yml, .github/workflows/netlify.yml
See https://github.com/dfinity/agent-rs/pull/52
The conventional commits workflow needs a secret with write access in order to be able to update the commit status.  Using pull_request_target achieves this, which is fine since this step doesn't need the branch contents anyway.
The netlify step also needs write access in order to comment on the PR.  Using pull_request_target rather than pull_request means that docs from the base branch will be uploaded rather than from the PR branch.  This is also what is done in agent-rs, and I think it's wrong there (too), but in the interest of having PRs from forks be able to pass at all, I am making them consistent.
=> ci: use pull_request_target for workflows that need it

examples/chess/dfx.json, examples/chess/package-lock.json, examples/chess/package.json, examples/chess/src/chess_rs_assets/index.html, examples/chess/src/chess_rs_assets/integration.tsx, examples/chess/src/declarations/chess_rs/chess_rs.did, examples/chess/src/declarations/chess_rs/chess_rs.did.d.ts, examples/chess/src/declarations/chess_rs/chess_rs.did.js, examples/chess/src/declarations/chess_rs/index.js, examples/chess/src/declarations/chess_rs_assets/assetstorage.did, examples/chess/src/declarations/chess_rs_assets/chess_rs_assets.did, examples/chess/src/declarations/chess_rs_assets/chess_rs_assets.did.d.ts, examples/chess/src/declarations/chess_rs_assets/chess_rs_assets.did.js, examples/chess/src/declarations/chess_rs_assets/index.js, examples/chess/webpack.config.js
The new frontend code is from a previous effort in https://github.com/dfinity/cdk-rs/commit/069156cf4555203085f5846b7f1e16c6441b4957.
After `dfx deploy --no-wallet`, run `npm start` and open the url like `http://localhost:8080/`. A chess board will be showed in browser.
=> fix: chess example frontend

src/ic-cdk/src/api/call.rs, src/ic-cdk/src/api/ic0.rs
`ic0.rs` contains all system APIs defined in the spec.
`call.rs` wrap some of them into safe rust functions.
Should we provide wrapped functions for all APIs?
Also, the APIs in the spec use `i64` while the wrapped functions use `u64`. What guarantees/assumptions do we have for such type cast?
=> feat: add system APIs for 128 bits cycles

README.md, src/ic-cdk-macros/README.md, src/ic-cdk/README.md
The README files are kept minimal with links to https://smartcontract.org and https://docs.rs.
=> docs: overhaul README files

docs/modules/rust-guide/pages/rust-quickstart.adoc
In the step Register, build, and deploy your project it's possible to fail because wasm32-unknown-unknown component isn't installed. Added a step 2 to handle that
=> docs: Add a step to install wasm32-unknown-unknown

src/ic-cdk/src/api.rs, src/ic-cdk/src/api/call.rs, src/ic-cdk/src/api/ic0.rs
Following up on our discussion regarding the multivalue target feature support, we have decided to update the experimental System Api and not rely on this feature anymore. 
This MR updates the SystemAPI according to the Public Spec: https://github.com/dfinity-lab/ic-ref/pull/381.
=> feat: update system API for 128 bit cycles

examples/profile/src/profile_inter_rs/lib.rs, examples/profile/src/profile_inter_rs/profile.did, examples/profile/src/profile_rs/lib.rs, examples/profile/src/profile_rs/profile.did
The `rust_profile` tutorial is a bit hard to trace without a
description of why we should:
```
type Profile = Profile_2
```
The tutorial still works without this line with refactoring `Profile_2` to `Profile`.
Please let me know if there are other intentions. (I'm very much interested to see when there is a case)
=> fix: deleted `Profile_2` to `Profile`

src/ic-cdk/src/printer.rs
This PR enhances the custom panic hook to `trap` on top of printing the error. The reason for doing this is that it results in a better error message that gets back to the user. Instead of a generic "trapped: unreachable" we will get a more useful "trapped explicitly: error message".
=> feat: Trap in setup panic hook

docs/modules/rust-guide/examples/mul-deps/deps-main.rs, docs/modules/rust-guide/examples/mul-deps/mul-deps-dfx.json
Switched the attribute of read() to query as it is otherwise inconsistent with the suggested candid file.
=> docs: fix attribute of read()

src/ic-ledger-types/src/lib.rs
Marking these functions as const allows them to be used in const contexts.
Eg. `const REGISTRATION_FEE: Tokens = Tokens::from_e8s(100_000_000);`
=> feat: mark suitable functions as const

src/ic-ledger-types/src/lib.rs
These 2 canister Ids are needed for creating neurons and minting cycles.
I took the canister Ids from here - https://github.com/dfinity/ic/blob/master/rs/nns/canister_ids.json
=> feat: expose constants for the governance and cycles minting canister Ids

src/ic-cdk-macros/src/export.rs, src/ic-cdk/src/futures.rs, src/ic-cdk/src/lib.rs
This PR provides the functionality of `block_on` under a better name,
`spawn`. The `block_on` function is marked as deprecated in favour of
`spawn`.
Closes #7 and #174.
=> refactor: deprecate block_on in favour of the new spawn function

README.md, docs/modules/rust-guide/pages/rust-profile.adoc, docs/modules/rust-guide/pages/rust-quickstart.adoc, examples/asset_storage/src/asset_storage_rs/Cargo.toml, examples/chess/src/chess_rs/Cargo.toml, examples/counter/src/counter_rs/Cargo.toml, examples/counter/src/inter2_rs/Cargo.toml, examples/counter/src/inter_rs/Cargo.toml, examples/print/src/print_rs/Cargo.toml, examples/profile/src/profile_inter_rs/Cargo.toml, examples/profile/src/profile_rs/Cargo.toml, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/Cargo.toml, src/ic-ledger-types/Cargo.toml
This PR removes the default features from `ic-cdk` and `ic-cdk-macros` which in turn enable the `cdk` feature in `candid`.
The default features are tricky because they end up getting enabled in situations where you don't want them to, e.g. if you have a dependency which in turn depends on candid but without enabling this feature, then you end up with code that doesn't compile (because there are two crates pulling the same one, once with the feature on and once without). This results in not being able to use `ic-cdk` and `ic-cdk-macros` with e.g. parts of the `ic` repository which makes certain things, that should be easy quite, hard to implement in your canister. 
Even worse, if you try to disable default features when importing `ic-cdk` and `ic-cdk-macros`, you actually still end up …
=> chore: Remove default features

src/ic-ledger-types/CHANGELOG.md, src/ic-ledger-types/Cargo.toml
=> chore: publish ic-ledger-types v0.1.1

rust-toolchain.toml
Sync this file and the CI configuration.
=> chore: Add rust-toolchain.toml and point to 1.55.0

docs/modules/rust-guide/examples/profile-tutorial/profile.rs, examples/asset_storage/src/asset_storage_rs/lib.rs, examples/counter/src/counter_rs/lib.rs, examples/profile/src/profile_rs/lib.rs, src/ic-cdk-macros/src/export.rs, src/ic-cdk-macros/src/lib.rs, src/ic-cdk/src/api/call.rs
Adds a `reply` field to `ic_cdk_macros`'s export macros, which controls whether `ic0.msg_reply` is called by the macro. If it is not, the canister function must (and therefore can) call that function itself. 
Also adds an `Empty` type to `ic_cdk::api::call`, for annotating not-physically-returning functions with the type they semantically return, for use with the former feature.
=> feat: Allow configuring export macros to not reply

src/ic-cdk/src/api/call.rs
This allows people to use `call_raw` without ever having to clone the bytes.
=> feat: Take slice rather than owned Vec as input arg

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api.rs, src/ic-cdk/src/api/call.rs
Implements user-facing versions of `ic0.msg_cycles_available128`, `ic0.msg_cycles_refunded128`, `ic0.msg_cycles_accept128`, and  `ic0.call_cycles_add128`.
Also adjusts `canister_balance128` to use a u128 as the buffer instead of `vec![0u8; 16]`.
=> feat: Implement remaining 128-bit functions

src/ic-cdk-optimizer/CHANGELOG.md, src/ic-cdk-optimizer/src/main.rs
Currently, the optimizer will only select stdin if no file is specified, which takes special effort to script around, and does not support stdout. This adds `-` input and output 'paths', which explicitly read from stdin and write to stdout respectively, following unix command conentions.
The interface also requires an output parameter, even though its primary usage is to overwrite the original file. This changes that so the output, if unspecified, will default to the input.
=> feat: Add stdin param and auto-select output file

src/ic-cdk-macros/src/lib.rs
This adds an example and quick explanation of how arguments are dealt
with in the `init` macro.
=> docs: Add example of using init args

src/ic-cdk/src/api/call.rs, src/ic-cdk/src/futures.rs
Adds a call to ic0.call_on_cleanup which signals the waker to drop the future without executing it. User cleanup code can be executed in a destructor via `scope-guard` or similar. This fixes the 'don't panic after awaiting' issue.
=> feat: Add cleanup code in case of await trap

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
Rust futures do nothing unless polled. This means that currently, call_raw will call the function whether it's awaited or not (since it is a manual future), but call/call_with_payment only actually make the call if awaited (since it is an `async fn`). This changes the implementation to have consistent behavior across the three function flavors (the caller can still disable this behavior by wrapping it in their own async block). As a bonus this no longer lifetimes the resulting future to the canister method name.
=> fix: Run inter-canister calls without awaiting

.github/workflows/examples.yml, .github/workflows/fmt.yml, .github/workflows/lint.yml, .github/workflows/test.yml, rust-toolchain.toml, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-macros/src/export.rs, src/ic-cdk-macros/src/import.rs, src/ic-cdk-macros/src/lib.rs, src/ic-cdk-macros/tests/compile_fail/only_function.stderr, src/ic-cdk-optimizer/Cargo.toml, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/stable.rs, src/ic-certified-assets/Cargo.toml, src/ic-certified-map/Cargo.toml, src/ic-ledger-types/Cargo.toml
This updates the CI and toolchain file to 1.58.1, adds the new MSRV key to Cargo.toml, and sets the crate editions to 2021 edition. It also fixes an instance of UB identified by 1.58 clippy.
=> chore: Update Rust to 1.58.1

src/ic-cdk/src/api/stable.rs
Adds a warning to the `stable_write` method so that developers are made aware of the scenario in which it panics.
We were burnt by this in OpenChat and we'd like to ensure no other devs fall into the same trap.
=> docs: Add warning to `stable_write` explaining scenario in which it panics

.github/workflows/examples.yml, examples/asset_storage/tests/basic.bats, examples/chess/tests/basic.bats
Update `dfx` used in CI to 0.9.3. Old `dfx` is blocking #240 
CI
=> chore: Update dfx to 0.9.3 in CI

src/ic-cdk/src/api/stable.rs
Adds a new helper method, `grow_then_write_stable_bytes`, which simplifies writing bytes to stable memory by first growing the stable memory size if needed.
Also fixes a small bug where `StableWriter` was requesting more memory pages than needed (prior to this commit it would always request the total amount needed rather than only the incremental amount needed).
The `grow_then_write_stable_bytes` function was first implemented in OpenChat where we thoroughly tested it, upgrading canisters multiple times and adding lots of data between upgrades. After each upgrade we could see that the `stable_memory_size` value for the affected canister had increased on the replica dashboard.
This function is now running in the production OpenChat deployment.
I have also locally deployed a version of …
=> feat: Add `grow_then_write_stable_bytes` helper method

src/ic-ledger-types/CHANGELOG.md, src/ic-ledger-types/src/lib.rs
We add a TryFrom instance from [u8; 32] to AccountIdentifier that checks if the bytes has a correct CRC-32 hash. 
This is a often required feature for an application that accepts account bytes from user input.
Also the ICP ledger canister itself will fail if CRC-32 is wrong. It is better to prevent wrong input in the construction. 
A simple unit test is added.
=> feat: Add a TryFrom instance for AccountIdentifier that checks CRC-32

src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/stable.rs, src/ic-cdk/src/api/stable/canister.rs, src/ic-cdk/src/api/stable/tests.rs
This adds a new stable memory writer called `BufferedStableWriter` which first buffers bytes in canister memory and only flushes those bytes to stable memory when the buffer becomes full.
Allocating additional memory and making system calls (`stable_grow` and `stable_write`) are both expensive operations, this writer minimises both.
There are unit test which cover the new `BufferedStableWriter` and the existing `StableWriter`.
I have also tested this locally and have successfully performed a few canister upgrades, adding data between each upgrade.
=> feat: Add `BufferedStableWriter` which aims to minimise system calls

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/stable.rs, src/ic-cdk/src/api/stable/tests.rs
This follows on from the `BufferedStableWriter` introduced in #245 by adding an equivalent `BufferedStableReader`.
The current `StableReader` reads the entire stable memory into a Vec on the heap, if we just want to deserialize stable memory then this is very wasteful as it allocates lots of memory which is only used temporarily, but then must be paid for from then on by the canister.
The new `BufferedStableReader` allocates a buffer and then reads from stable memory into that buffer, deserialization can happen incrementally each time the buffer is filled.
This involves more reads from stable memory but allocates less memory, allocating memory is far slower than reading so the end result is that this new version is significantly faster as well as being cheaper for the canister.
There are …
=> feat: Add `BufferedStableReader` for efficient reading from stable memory

e2e-tests/Cargo.toml, e2e-tests/canisters/async.rs, e2e-tests/tests/e2e.rs, src/ic-cdk/src/api/call.rs
This change adds an end-to-end test checking that the CDK frees
canister resources if the canister traps after an async call.
This feature was implemented in https://github.com/dfinity/cdk-rs/pull/232.
The test revealed that the feature is broken, so this PR also fixes the
cleanup logic to make the test pass.
=> chore(SDK-417): add an e2d test for async cleanup

src/ic-certified-assets/assets.did, src/ic-certified-assets/src/lib.rs
This change introduces a new test that checks that the certified assets
canister library satisfies the assets.did interface expected by the dfx.
The test revealed a minor discrepancy: method "delete_asset" was called
"delete_contents" for some reason. Apparently, dfx never invokes this
method.
=> chore: add asset canister did interface check

src/ic-certified-assets/src/lib.rs, src/ic-certified-assets/src/rc_bytes.rs, src/ic-certified-assets/src/state_machine.rs, src/ic-certified-assets/src/tests.rs, src/ic-certified-assets/src/types.rs, src/ic-certified-assets/src/url_decode.rs
This change is an extensive refactoring of the `ic-certified-assets` package.
The motivation for this change is to make the code more testable and
organized before adding caching logic.
The general idea behind the refactoring is to split out the "state
machine" logic into pure code that does not depend on Rust CDK and
accepts all the environment (time, certificates, etc.) as function
parameters. This logic moved to `state_machine.rs`.
`lib.rs` now contains the minimal glue to connect the state machine to
the Rust CDK interface. Eventually, this part should move back to
https://github.com/dfinity/certified-assets, making
the `ic-certified-assets` package independent from Rust CDK.
The refactoring does not affect the certification logic; all we do is
moving the code around, improving …
=> refactor: move pure assets certification code into a module

src/ic-certified-assets/src/rc_bytes.rs, src/ic-certified-assets/src/state_machine.rs, src/ic-certified-assets/src/tests.rs
This change implements [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) caching headers support in the ic-certified-assets package.
=> feat: support ETags in certified assets

src/ic-certified-assets/assets.did, src/ic-certified-assets/src/state_machine.rs, src/ic-certified-assets/src/tests.rs, src/ic-certified-assets/src/types.rs
This change extends the certified assets canister interface to support
setting max_age field for an asset.
If the field is present, the canister will translate it into
"Cache-Control: max-age={max_age}" header.
=> feat: add support for max_age field

src/ic-certified-assets/CHANGELOG.md, src/ic-certified-assets/Cargo.toml, src/ic-certified-assets/README.md
Release version 0.2.0 of `ic-certified-assets`.
=> chore: release ic-certified-assets 0.2.0

src/ic-certified-assets/CHANGELOG.md, src/ic-certified-assets/Cargo.toml, src/ic-certified-assets/README.md, src/ic-certified-assets/src/lib.rs
This change makes the StableState type from ic-certified-assets package
public again. Making it private was a bug that prevents us from
upgrading the certified assets canister to a newer version of
ic-certified-assets.
=> fix: make StableState public again

src/ic-certified-assets/CHANGELOG.md, src/ic-certified-assets/README.md, src/ic-certified-assets/src/state_machine.rs, src/ic-certified-assets/src/tests.rs
This change fixes the handling of ETag header values.
The standard expects hashes to have quotes around them, so the canister
logic produced and parsed asset hashes incorrectly.
=> fix: certified assets: parse and produce ETag headers with quotes

e2e-tests/Cargo.toml, e2e-tests/canisters/reverse.rs, e2e-tests/tests/e2e.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
This patch makes `arg_data_raw` public and adds `reply_raw` to provide a way to read the raw argument bytes of a method and to reply with raw bytes.
=> feat: adds serialization-agnostic API for reading arguments and replying

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api.rs, src/ic-cdk/src/api/call.rs
> This finding was marked as a False Positive and its Overall Risk rating was reduced to Informational since it was pointed out that the compiler was able to unambiguously infer the data
type due to the function calls following the array declaration. For example, the only From trait
implemented for Principals converts a byte array into a Principal, and there are currently
no other try_from implementations. Nevertheless, consider following the recommendation
outlined in this finding to remove any potential ambiguity.
The rust complier is able to infer the type of `u8`.  Marking it more explicitly helps reduce ambiguity.
Fixes #79
CI. This PR should not change any behavior.
=> fix: use explicitly type u8 in vector initialization

src/ic-cdk-macros/src/import.rs, src/ic-cdk/CHANGELOG.md
In dfinity/sdk#2032, the environment variables were unified to always be `CANISTER_CANDID_PATH_{name}`. This removes the usage of the deprecated version, `CANISTER_CANDID_{name}`.
=> fix: switch to correct DFX environment variable

e2e-tests/canisters/reverse.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
Add public function `arg_data_raw_size`. 
Useful for checking the size of the arg-data before deserializing or copying to a vector.
The test for this function is put into the reverse-canister test, by making the reverse method check `assert_eq!(arg_data_raw_size(), arg_data_raw().len())`.
=> feat: public function: arg_data_raw_size

e2e-tests/canisters/reverse.rs, e2e-tests/tests/e2e.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
The current implementation of `reply_raw` does not skip the call to `msg_reply_data_append` even if the passed bytes are empty. The problem with this is that while all functions are expected to call `reply`, not all functions are allowed to reply with data. The current patch introduces a simple check and skips calling `msg_reply_data_append` if no bytes were provided.
Unit test added.
=> fix: do not append reply data on empty buffer

src/ic-ledger-types/CHANGELOG.md, src/ic-ledger-types/src/lib.rs
The ledger has a relatively new method, `token_symbol`, this PR makes it easy for devs to make a call to that method.
I have been using this successfully within the `TransactionNotifier` (https://github.com/open-ic/transaction-notifier)
=> feat: integrate with the ledger's `token_symbol` method

.github/workflows/e2e.yml, .github/workflows/examples.yml, .github/workflows/fmt.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Aggregate the status checks so that we can add required statuses that do not specify a rust version or particular runner OS.
=> chore: aggregate matrix checks for required statuses

.github/workflows/e2e.yml, .github/workflows/examples.yml, .github/workflows/fmt.yml, .github/workflows/lint.yml, .github/workflows/test.yml, e2e-tests/Cargo.toml, e2e-tests/canisters/api_call.rs, e2e-tests/src/lib.rs, e2e-tests/tests/e2e.rs, rust-toolchain.toml, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-optimizer/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/call.rs, src/ic-cdk/src/api/ic0.rs, src/ic-certified-assets/Cargo.toml, src/ic-certified-map/Cargo.toml, src/ic-ledger-types/Cargo.toml
Add support for new system API `performance_counter`:
```rust
ic_cdk::api::call::performance_counter(counter_type: u32) -> u64
```
The rust toolchain is updated to 1.60.0 in consistent with `ic`.
e2e test
=> feat: support performance_counter

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/stable.rs, src/ic-cdk/src/api/stable/canister.rs
The `with_memory()` constructors of `StableWriter` and `StableReader` will be practically useful.
=> feat: make CanisterStableMemory public

e2e-tests/canisters/api_call.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api.rs
This change attempts to make performance_counter API a bit easier to
find and use:
1. Move `performance_counter` from `ic_cdk::api::call` to
`ic_cdk::api` because the counter has nothing to do with making
calls.
2. Introduce an alias for `performance_counter(0)`,
`instruction_counter()`. It's much better on the eye and doesn't
force the code reader to learn about valid inputs for
`performance_counter`.
=> refactor: move performance_counter to ic_cdk::api module

src/ic-certified-assets/CHANGELOG.md, src/ic-certified-assets/Cargo.toml, src/ic-certified-assets/assets.did
Continuation of https://github.com/dfinity/cdk-rs/pull/282. The previous PR [incorrectly defined new field in candid spec](https://github.com/dfinity/cdk-rs/blob/7beb1b6e5473ae07337a227059523ff9a376f05f/src/ic-certified-assets/assets.did#L10), which resulted in an incorrect generation of types in e.g. TS:
```ts
export interface CreateAssetArguments {
key: Key;
content_type: string;
headers: [] | [HeaderField];
max_age: [] | [bigint];
}
export declare type HeaderField = [string, string];
```
This PR fixes that, helping generate correct types (again, TS as an example):
```ts
export interface CreateAssetArguments {
'key' : Key,
'content_type' : string,
'headers' : [] | [Array<HeaderField>], // fixed
'max_age' : [] | [bigint],
}
export type HeaderField = [string, string];
```
manually …
=> fix: candid spec to support setting multiple custom HTTP headers on asset creation

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
This change fixes the commentary for ManualReply that mentioned
non-existing `#[query(reply = false)]` syntax.
The correct syntax is `#[query(manual_reply = true)]`.
=> fix(doc): update comments for ManualReply

src/ic-cdk/src/api/call.rs
To test the canister HTTP feature, we run a proxy canister that should return the response 1:1 and `RejectionCode` can not be candid encoded.
=> feat: Derive CandidType for RejectionCode

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
We should also implement common traits to make `RejectionCode` useful. Feel free to include this whenever you make the next release.
=> feat: Implement common traits for RejectionCode

src/ic-cdk/src/api/call.rs
Explicitly states that the function traps if decoding fails.
=> chore: Clarify `arg_data()` behavior on failure

e2e-tests/canisters/api_call.rs, e2e-tests/tests/e2e.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
I :heart: the ManualReply interface because it gives so much flexibility.
The type misses on short cut: reject and produce a manual reply object.
This change adds the missing shortcut.
I've added an end-to-end test.
=> feat: ManualReply::reject API

e2e-tests/canisters/async.rs, e2e-tests/tests/e2e.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
This change maps decoding failure in the call() function to
CanisterError rejection code. This way canisters have a chance to handle
decoding failures gracefully.
The change includes an end-to-end test.
=> fix: do not trap in call() if decoder fails

README.md
Quick PR to fix broken tutorial links in the readme file. 
N/A
=> fix: update tutorial links in readme

.github/workflows/ci.yml, .github/workflows/examples.yml, Cargo.toml, examples/build.sh, src/ic-cdk-optimizer/CHANGELOG.md, src/ic-cdk-optimizer/Cargo.toml, src/ic-cdk-optimizer/README.md
To end the life of ic-cdk-optimizer, we remove it from rust workspace and CI.
Also, close #187.
CI
=> chore: deprecate optimizer

.github/workflows/examples.yml, src/ic-certified-map/CHANGELOG.md, src/ic-certified-map/Cargo.toml
The `sha2` dependency has been updated to the latest version.
Tested by running unit tests.
=> chore: update outdated sha2 dependency of ic-certified-map

.github/workflows/ci.yml, .github/workflows/conventional-commits.yml, .github/workflows/examples.yml
Similar to https://github.com/dfinity/sdk/pull/2573.
=> chore(ci): cancel previous CI run after new push

examples/management_canister/src/caller/lib.rs, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/management_canister/main/mod.rs
Fix wrong number of cycles charged by `create_canister` (1T -> 0.1T).
Add `create_canister_with_extra_cycles`.
Example test.
=> feat: specify cycles when create canister

src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic0/Cargo.toml, src/ic0/README.md, src/ic0/util/ic0build.rs
Existing build script directly write source file which is not allowed in bazel. And it doesn't make sense to run build script for every dependent.
The new approach is to make the build script an example binary. `ic0` maintainer should just execute `cargo run --example=ic0build` locally to update `ic0.rs`.
Also this should fix the [document building issue](https://docs.rs/crate/ic-cdk/0.6.2/builds/655852).
CI
=> fix: no build script for ic0

src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/stable/mod.rs, src/ic-cdk/src/api/stable/tests.rs
Expose offsets in reader and writer. The change is useful to use stable storage with common serialization libraries.
Fixes #323
Unit tests
=> feat: expose offsets in reader and writer

.github/workflows/examples.yml, examples/management_canister/src/caller/lib.rs, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/management_canister/http_request.rs
Updates CDK in the area of `http_request` through management canister.  Adds `context` field to callback function for response transformation. 
- Updated tests in CDK
- Tested with newest replica + sample dapp for `http_request` feature
=> chore: BREAKING CHANGE: Update for HTTPS Outcalls transform function with context.

src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/stable/mod.rs, src/ic-cdk/src/api/stable/private.rs, src/ic-cdk/src/api/stable/tests.rs
* Implement io::Seek
* Add StableIO structure that implements both io::Read, and io::Write
Co-authored-by: Dmitry Demin <dmitry.demin@outlook.com>
The change generalizes the StableWriter and StableReader APIs, while maintaining backwards compatibility, to add support for 64-bit std::io::Read/Write implementations as well as implementing the std::io::Seek implementation.
This greatly increases the utility of stable storage, allowing it to be used for more complex read/write patterns, as well as taking advantage of the greater capacity.
Fixes #333 and #334 
Unit tests + testing with the dscvr canister.
=> feat: generalize stable storage API by adding 64-bit support for std:io traits

.github/workflows/ci.yml, src/ic0/Cargo.toml, src/ic0/src/ic0.rs, src/ic0/util/ic0build.rs, src/ic0/util/work.rs
For some use cases of test, `ic-cdk` targets not `wasm32`. System API should still be linkable symbols.
`cargo build --example=work` which target host OS.
=> fix: ic0 can build on non-wasm

library/ic-certified-map/CHANGELOG.md, library/ic-certified-map/Cargo.toml, library/ic-certified-map/src/rbtree.rs
Make `RbTree::new` and `RbTree::is_empty` const. Doing this requires removing the bounds from the `RbTree` declaration, but wider bounds and adding `const` are both backwards compatible.
`cargo test`
=> refactor: make `RbTree` more `const`

README.md, docs/modules/rust-guide/examples/counter-tutorial/counter.rs, docs/modules/rust-guide/examples/intercanister-tutorial/profile-interoperation.rs, docs/modules/rust-guide/examples/mul-deps/deps-main.rs, docs/modules/rust-guide/examples/profile-tutorial/profile.rs, docs/modules/rust-guide/pages/rust-quickstart.adoc, e2e-tests/canisters/api_call.rs, e2e-tests/canisters/async.rs, e2e-tests/canisters/simple_kv_store.rs, examples/asset_storage/src/asset_storage_rs/lib.rs, examples/chess/src/chess_rs/lib.rs, examples/counter/src/counter_rs/lib.rs, examples/counter/src/inter2_rs/lib.rs, examples/counter/src/inter_rs/lib.rs, examples/management_canister/src/caller/lib.rs, examples/print/src/print_rs/lib.rs, examples/profile/src/profile_inter_rs/lib.rs, examples/profile/src/profile_rs/lib.rs, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-macros/src/import.rs, src/ic-cdk-macros/src/lib.rs, src/ic-cdk-macros/tests/compile_fail/lifecycle_functions_should_have_no_return.rs, src/ic-cdk-macros/tests/compile_fail/no_generic.rs, src/ic-cdk-macros/tests/compile_fail/no_self.rs, src/ic-cdk-macros/tests/compile_fail/only_function.rs, src/ic-cdk-macros/tests/pass/blank_methods.rs, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/management_canister/http_request.rs, src/ic-cdk/src/lib.rs
This PR removes ic-cdk-macros's dependency on ic-cdk, which was only used for an intra-doc link and the reexported `Principal` more easily accessed from Candid. This enables ic-cdk to depend on ic-cdk-macros and reexport its macros; with this change, users no longer need to declare two dependencies for the full CDK.
=> feat: reverse dependency order

.github/workflows/ci.yml, e2e-tests/Cargo.toml, e2e-tests/canisters/async.rs, e2e-tests/tests/e2e.rs, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-macros/src/export.rs, src/ic-cdk-macros/src/lib.rs, src/ic-cdk-macros/tests/pass/blank_methods.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic0/Cargo.toml
This PR adds support for composite queries, via `#[query(composite = true)]`. Composite queries can call other query functions, but cannot be called in replicated mode.
For more details about composite queries, please check these forum threads:
* https://forum.dfinity.org/t/proposal-composite-queries/15979
* https://forum.dfinity.org/t/inter-canister-query-calls-community-consideration/6754
Implements SDK-829.
=> feat: Implement composite queries

examples/asset_storage/src/asset_storage_rs/Cargo.toml, examples/chess/src/chess_rs/Cargo.toml, examples/chess/src/chess_rs/getrandom_fail.rs, examples/chess/src/chess_rs/lib.rs, examples/counter/src/counter_rs/Cargo.toml, examples/counter/src/inter2_rs/Cargo.toml, examples/counter/src/inter_rs/Cargo.toml, examples/print/src/print_rs/Cargo.toml, examples/profile/src/profile_inter_rs/Cargo.toml, examples/profile/src/profile_rs/Cargo.toml, src/ic-cdk/CHANGELOG.md
Pleco is no longer maintained, it has outstanding issues and hasn't had a new contribution in two and half years.  
[Tanton](https://github.com/chase-manning/tanton) is a fork of Pleco that is backward compatable and actively maintained.  
This PR changes from using Pleco to using Tanton.
All of the Pleco tests were kept with Tanton and all are passing on `stable`, `alpha` and `nightly` versions of cargo.
The CI build should run in this PR so should test everything needed from the `cdk-rs` side.
=> refactor: change from pleco to tanton

src/ic-cdk/src/api/mod.rs
This mentions that the value returned by `time()` is nanoseconds, elapsed since the epoch.
=> docs: Add documentation for time()

library/ic-ledger-types/src/lib.rs, src/ic-cdk/CHANGELOG.md
This PR makes it trivial to convert a Principal into a Subaccount.
Principals are often used as Subaccounts to differentiate between funds controlled by the same Principal (eg. when creating a canister the Subaccount is the Principal of the new canister's controller).
I used this forked version to successfully top up a canister using the canister's Principal as the Subaccount.
I have also added a unit test.
=> feat: impl From<Principal> for Subaccount

.github/workflows/ci.yml, .github/workflows/examples.yml, e2e-tests/Cargo.toml, e2e-tests/canisters/async.rs, e2e-tests/src/lib.rs, e2e-tests/tests/e2e.rs, library/ic-certified-map/src/rbtree.rs, library/ic-certified-map/src/rbtree/test.rs, rust-toolchain.toml, src/ic-cdk-macros/src/import.rs, src/ic-cdk-macros/src/lib.rs, src/ic-cdk/src/api/stable/tests.rs, src/ic-cdk/src/timer.rs, src/ic0/src/lib.rs
Fix all the new `clippy` warnings.
=> chore: update the toolchain and `ic-state-machine-tests`

e2e-tests/canisters/timers.rs, e2e-tests/tests/e2e.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/timer.rs
This MR retries timers execution after a transient system error.
Fixes RUN-527
=> fix: RUN-527: retry timers execution

library/ic-ledger-types/CHANGELOG.md, library/ic-ledger-types/Cargo.toml, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-timers/CHANGELOG.md, src/ic-cdk-timers/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml
ic-cdk-timers v0.1.0
ic-cdk v0.7.0
ic-ledger-types v0.3.0
=> chore: first release ic-cdk-timers

.github/workflows/examples.yml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/stable/mod.rs
Add `pub` to `WASM_PAGE_SIZE_IN_BYTES` definition
Why wasn't it `pub`?
Not tested.
=> feat: WASM_PAGE_SIZE_IN_BYTES made pub

README.md
Point documentation site to current url [https://internetcomputer.org/docs](https://internetcomputer.org/docs) in README instead of smartcontracts.org.
=> docs: fix link to documentation site of the IC

src/ic-cdk/src/api/management_canister/http_request.rs
This PR improves the doc comment of the `max_response_bytes` field of canister http requests to explain how it affects pricing and recommend that users set it to as low as possible value.
=> chore: Improve doc comments for max_response_bytes

.github/workflows/ci.yml
We use `-Dclippy::all` in CI, which only causes a failed check for lints clippy enables by default, and not any we've specifically enabled like `clippy::missing_safety_doc`. The correct flag for this is `-Dwarnings`.
=> chore: Fail CI for explicitly enabled clippy warnings

src/ic-cdk/src/api/call.rs
This PR is a modification to #391 that allows argument data to be borrowed. It does so by changing our userdata pointer from an Arc to a Weak; if the caller drops the borrowed data, the Weak will fail to upgrade, preventing a dangling pointer.
@lwshang @mraszyk
=> Add borrowed arg data to lazy calls

src/ic-cdk/src/api/call.rs
Missed 286faae in #391 that should have been reverted. Per the Future docs, if a future needs to be polled multiple times, it should only wake the most recently provided waker.
=> fix: Always overwrite waker

library/ic-ledger-types/CHANGELOG.md, library/ic-ledger-types/Cargo.toml, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-timers/CHANGELOG.md, src/ic-cdk-timers/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic0/Cargo.toml, src/ic0/ic0.txt
~Only bumped the patch version though there is http outcall API change.~
~Projects using the http outcall API will need modify their code accordingly. But other projects will get benefit from this upgrade directly.~
The `interface-spec` hasn't got a new version since v0.18.9 (2022-12). I updated `ic0.txt` as v0.18.10 with the latest content on master branch.
The crates depend on `ic-cdk` also bump minor version.
=> chore: release ic-cdk v0.8.0

src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/management_canister/http_request.rs
This fixes the cfgs to no longer pretend the feature is enabled when being documented (as this is incompatible with the feature requiring optional dependencies) and instead just adds `--all-features` to the doc build to get the same effect.
=> fix: Fix docs.rs build

e2e-tests/Cargo.toml, e2e-tests/canisters/canister_info.rs, e2e-tests/tests/e2e.rs, scripts/download_state_machine_binary.sh, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/management_canister/main/mod.rs, src/ic-cdk/src/api/management_canister/main/types.rs
This PR makes the following changes:
- Set caller's canister version in the field `sender_canister_version` of management canister call payloads so that the caller's canister version is recorded in the canister history.
- Add management canister types and call function for `canister_info` management canister call (`CanisterInfoRequest` and `CanisterInfoResponse`)  to support this new management canister call.
This PR adds a new test canister and integration test against `StateMachine`.
=> feat: set sender_canister_version and support canister_info

examples/management_canister/src/caller/lib.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/management_canister/bitcoin/mod.rs
SDK-1142
Bitcoin API charges the same amount of cycles no matter size of subnet. And the numbers are considering constants.
Handling cycles cost under the hood makes the API more convenient.
Once this PR merged, `ic-cdk` v0.9.1 will be released and v0.9.0 will be yanked from crates.io
Example test
=> feat: Bitcoin API handles cycles cost under the hood.

examples/management_canister/src/caller/lib.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/management_canister/bitcoin/mod.rs, src/ic-cdk/src/api/management_canister/ecdsa/mod.rs
* Hardcodes the fee for `sign_with_ecdsa`, as it is a constant that will not change.
* ~Removes the `bitcoin_` prefix from the bitcoin method endpoints. These methods are already encapsulated in a `bitcoin` module, so the prefix is redundant.~
=> feat: Hardcodes the fee for `sign_with_ecdsa`.

e2e-tests/canisters/async.rs, scripts/download_state_machine_binary.sh
#365 changed the `panic_after_async` test so that it does not hold a resource open across the await point, but the thing it's supposed to be testing is that resources are freed after await points. This reverts that change.
=> chore: Check panic after await freeing resources

examples/management_canister/src/caller/lib.rs
This PR update the function `http_request_required_cycles` from `examples` to use the new proposed formula specified [here](https://forum.dfinity.org/t/a-new-price-function-for-https-outcalls/20838).
=> chore: Update example http_request_required_cycles

src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-macros/src/export.rs, src/ic-cdk-macros/src/lib.rs, src/ic-cdk-macros/tests/compile_fail/no_guard_function_for_lifecycle.rs, src/ic-cdk-macros/tests/compile_fail/no_guard_function_for_lifecycle.stderr
Reported in this [forum post](https://forum.dfinity.org/t/guard-functions-should-not-be-allowed-in-init-pre-upgrade-and-post-upgrade/21731).
`trybuild` test
=> fix: only update/query macros can take guard function

.github/workflows/ci.yml, .github/workflows/examples.yml, Cargo.toml, rust-toolchain.toml
ProdSec recommends bumping the Rust version to 1.71.1
CI
=> chore: update Rust toolchain

.github/workflows/ci.yml, .github/workflows/examples.yml, Cargo.toml, rust-toolchain.toml
> For library projects, we should not change the rust-version line in Cargo.toml. Because that field restricts the minimum supported Rust version (MSRV) of the crate which will enforce the dependent crates/projects to upgrade their MSRV too, i.e. the change is contagious. We should avoid updating the field as mush as we can. And we should use the same version in CI to guarantee the MSRV.
Revert MSRV and add some tips for maintenance.
=> chore: revert MSRV

src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/src/export.rs
Export composite query to Candid.
=> fix: export composite query correctly

.github/workflows/ci.yml, .github/workflows/examples.yml, .github/workflows/release-candid-extractor.yml, Cargo.lock, Cargo.toml, e2e-tests/Cargo.toml, rust-toolchain.toml, src/candid-extractor/Cargo.toml, src/candid-extractor/src/main.rs
MSRV is increased to 1.66.0 because `candid-extractor`'s dependency `wasmtime` requires it.
There will be only two places specify Rust toolchain version:
* Cargo.toml
* rust-toolchain.toml
They should sync with each other.
Check the actions log.
=> chore: unify Rust toolchain version

Cargo.lock, src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-macros/src/export.rs, src/ic-cdk-macros/src/lib.rs
Stateful macro crates can cause IDE errors when the IDE keeps a single instance of the macro crate loaded and runs it multiple times. This PR removes the last remaining global state from the macros.
=> fix: Remove global state from `ic-cdk-macros`

Cargo.lock, Cargo.toml, e2e-tests/canisters/api_call.rs, e2e-tests/tests/e2e.rs, ic0.txt, scripts/download_state_machine_binary.sh, src/candid-extractor/Cargo.toml, src/candid-extractor/ic_mock.wat, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/mod.rs, src/ic0/Cargo.toml, src/ic0/src/ic0.rs
SDK-1280
Include new `cycles_burn128()`  API method in `ic0` crate.
Provide a safe wrapper `cycles_burn` in `ic_cdk::api` module.
`candid_extractor` is also updated.
e2e with ic-state-machine-test
=> feat: cycles_burn 

Cargo.lock, Cargo.toml, src/ic-cdk-timers/Cargo.toml
Should have been part of #433. Fixes #436.
=> chore: Release ic-cdk-timers@0.5.1

library/ic-ledger-types/src/lib.rs
Adding the `icrc1_memo` field to the `Transaction` struct. The field was previously added to the `Transaction` struct in the ICP ledger.
Closes #444.
=> feat: Adding icrc1_memo field to the Transaction

Cargo.lock, Cargo.toml, scripts/download_state_machine_binary.sh, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/management_canister/main/types.rs
Adds support for [query statistics](https://forum.dfinity.org/t/community-consideration-explore-query-charging/19247/23?u=stefan-kaestle) to the Rust CDK.
The IC will periodically update the query statistics in the canister status as described in the [proposal](https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=123481).
There are multiple unit, system and e2e tests that test if query statistics are updated.
The canister status endpoint has been extended to contain those new statistics, but no further testing on the canister status side has been added.
=> feat: Added query stats to canister status endpoint

src/ic-cdk/src/api/management_canister/main/types.rs
It seems we forgot to make the members public when adding query stats to the `cdk`.
In order for the `struct` to be useful in canister code, those have to be pub.
=> fix: query stats: make members public

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/call.rs
This PR adds a function to check whether the async task is being canceled due to a trap. This allows e.g. implementing custom mutex poisoning.
=> feat: `is_recovering_from_trap`

Cargo.toml, e2e-tests/Cargo.toml, rust-toolchain.toml
Mirrors dfinity/agent-rs#479. Our Cargo.lock works with 1.66.0, but a new user's won't, and this eliminates the legacy crate index.
=> chore: Raise MSRV to 1.70.0

Cargo.lock, examples/profile/dfx.json, examples/profile/src/profile_inter_rs/build.rs, examples/profile/tests/basic.bats, src/ic-cdk-bindgen/CHANGELOG.md, src/ic-cdk-bindgen/Cargo.toml, src/ic-cdk-bindgen/src/lib.rs
- Resolve CANISTER_CANDID_PATH and CANISTER_ID from standardized environment variables (uppercase canister names).
- The support for legacy (non-uppercase) env vars is kept.
- It will be removed in next major release (v0.2).
examples/profile checks:
- canister names containing hyphens
- dfx v0.13.0 which only provides deprecated format env vars will cause warnings
=> fix(bindgen): look for standardized environment variables

.github/workflows/ci.yml, .github/workflows/examples.yml, examples/counter/src/inter2_rs/lib.rs, examples/counter/src/inter_rs/lib.rs, examples/profile/src/profile_inter_rs/lib.rs, examples/rust-toolchain.toml
Always running examples with latest `dfx` will help us find regression/incompatibility earlier.
Also the dependency actions are upgraded so that no more warnings about deprecated Node version.
examples
=> chore(ci): examples run with latest dfx

Cargo.lock, Cargo.toml, library/ic-ledger-types/CHANGELOG.md, library/ic-ledger-types/Cargo.toml, src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml
Also release:
- `ic-cdk-macros` v0.8.5
- `ic-ledger-types` v0.10.0
=> chore: release ic-cdk v0.13.0

Cargo.lock, src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml
`ic-cdk-macros` should have been bumped to `0.9.0` when released as `0.8.5`.
It caused the projects using `ic-cdk` v0.12 and `ic-cdk-macros` v0.8 broken. Because, `ic-cdk-macros` v0.8.5 actually generated code for `ic-cdk` v0.13.
=> chore: release ic-cdk v0.13.1 and ic-cdk-macros v0.9.0

examples/asset_storage/Cargo.toml, examples/asset_storage/src/asset_storage_rs/Cargo.toml, examples/asset_storage/tests/basic.bats, examples/chess/Cargo.toml, examples/chess/src/chess_rs/Cargo.toml, examples/chess/tests/basic.bats, examples/counter/Cargo.toml, examples/counter/src/counter_rs/Cargo.toml, examples/counter/src/inter2_rs/Cargo.toml, examples/counter/src/inter_rs/Cargo.toml, examples/counter/tests/basic.bats, examples/management_canister/.gitignore, examples/management_canister/Cargo.toml, examples/management_canister/tests/basic.bats, examples/print/Cargo.toml, examples/print/src/print_rs/Cargo.toml, examples/print/tests/basic.bats, examples/profile/Cargo.toml, examples/profile/src/profile_inter_rs/Cargo.toml, examples/profile/src/profile_rs/Cargo.toml, examples/profile/tests/basic.bats
- Fixed the bitcoin issue in the management_canister example.
- Added assertions to all examples.
- Improved identities management in the asset_storage example.
- Set all crates to 2021 edition and the workspaces to use resolver 2.
example.yml
=> chore: examples overhaul

e2e-tests/canisters/timers.rs, e2e-tests/tests/e2e.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/mod.rs
SDK-1544
Though we provide a timers suite in `ic-cdk-timers`, it is still useful to call `global_timer_set` system API directly.
This PR adds the safe wrapper:
```rust
pub fn set_global_timer(timestamp: u64) -> u64;
```
e2e test
=> feat: provide safe wrapper of global_timer_set in ic-cdk

.github/workflows/examples.yml, examples/management_canister/tests/basic.bats
SDK-1549
dfx v0.18.0 bundled bitcoin canister didn't work locally (also in CI).
I made a temp fix for CI in #473.
Now dfx v0.19.0 is released without the issue.
=> chore(ci): remove temporary fix for bitcoin integration canister

e2e-tests/Cargo.toml, e2e-tests/canisters/canister_info.rs, e2e-tests/canisters/chunk.rs, e2e-tests/tests/e2e.rs, scripts/download_state_machine_binary.sh, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/management_canister/main/mod.rs, src/ic-cdk/src/api/management_canister/main/types.rs
Adds `upload_chunk`, `stored_chunks`, `clear_chunk_store` and `install_chunked_code` to the management canister API.
I have tested this locally by uploading a wasm comprised of 3 chunks, the I queried `stored_chunks` which returned the chunks, then I called `install_chunked_code` which completed successfully, then I called `clear_chunk_store`, then I queried `stored_chunks` again and this time it was empty.
=> feat: add management canister methods for interacting with the chunk store

Cargo.lock, Cargo.toml, src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml
sync the version of ic-cdk and ic-cdk-macros
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
=> chore: release ic-cdk v0.13.2

src/ic-cdk-bindgen/CHANGELOG.md, src/ic-cdk-bindgen/src/lib.rs
When switching networks (e.g. `dfx canister build` vs `dfx canister build --ic`) then often the canister ids change, but cargo doesn't notice that the bindings need to be regenerated.
Not using `cargo:rerun-if-changed={candid_path_str}` because dfx likes to point to temporary copies of the files instead of the original ones, resulting in many unnecessary rebuilds.
Tested manually on a local copy
=> feat: Re-generate bindings if canister id or candid path change

Cargo.lock, src/ic-cdk-bindgen/CHANGELOG.md, src/ic-cdk-bindgen/Cargo.toml, src/ic-cdk-bindgen/src/code_generator.rs, src/ic-cdk-bindgen/src/lib.rs
SDK-1589
We are going to make `ic-cdk-bindgen` support more use cases, e.g. generating types only, generating bindings for canister implementation.
The first step is to move the Rust code generation logic from the candid_parser crate so that we can have complete control of Rust codegen.
The added `code_generator.rs` file was the [rust/candid_parser/src/bindings/rust.rs](https://github.com/dfinity/candid/blob/ae4d0f794a808b88f8b83da7eb96ca87b3d751d4/rust/candid_parser/src/bindings/rust.rs) in the candid crate.
The only difference:
```diff
diff cdk-rs/src/ic-cdk-bindgen/src/code_generator.rs candid/rust/candid_parser/src/bindings/rust.rs
0a1
> use super::analysis::{chase_actor, infer_rec};
3d3
< use candid_parser::bindings::analysis::{chase_actor, infer_rec};
```
Example tests
=> refactor!: move Rust code generation logic from candid_parser.

src/ic-cdk-macros/src/lib.rs, src/ic-cdk/src/api/stable/mod.rs
Replace `https://smartcontracts.org` with `https://internetcomputer.org`.
Fix #460
=> docs: replace deprecated URLs

e2e-tests/canisters/canister_info.rs, e2e-tests/canisters/management_caller.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/management_canister/main/types.rs
This adds `wasm_memory_limit` to `CanisterSettings` and `DefiniteCanisterSettings`.
The corresponding spec change:
- https://github.com/dfinity/interface-spec/pull/278
Ticket: SDK-1588
=> feat: Add `wasm_memory_limit` to the management canister

Cargo.lock, Cargo.toml, examples/print/tests/basic.bats, library/ic-certified-map/src/rbtree/test.rs, rust-toolchain.toml, src/candid-extractor/CHANGELOG.md, src/candid-extractor/Cargo.toml, src/candid-extractor/src/extract.rs, src/candid-extractor/src/main.rs
Use `clap` for CLI. So we get support for `-V`/`--version`  and `-h`/`--help` automatically.
Also in this PR:
- Add the changelog file for this bin crate.
- Upgrade `wasmtime` dependency to v19.
-  Require more recent rust toolchain, so bump to v1.75 as the sdk repo.
- `cargo update` to refresh the lock file.
Fixes #459
Added a test in examples/print
=> feat: candid-extractor supports --version

Cargo.lock, examples/counter/src/counter_rs/lib.rs, examples/counter/src/inter2_rs/build.rs, examples/counter/src/inter2_rs/lib.rs, examples/counter/src/inter_rs/build.rs, examples/counter/src/inter_rs/lib.rs, examples/profile/src/profile_inter_rs/build.rs, examples/profile/src/profile_inter_rs/lib.rs, src/ic-cdk-bindgen/Cargo.toml, src/ic-cdk-bindgen/src/code_generator.rs, src/ic-cdk-bindgen/src/error.rs, src/ic-cdk-bindgen/src/lib.rs
SDK-1622
The current API of `ic-cdk-bindgen` crate exposes many types from the dependency `candid_parser`. 
This rewrite is necessary for the upcoming "Trait-Bound Canister Development" feature. which will need Candid to Rust bindgen for various targets.
The targets will be supported:
- `Consumer`
- `Provider`
- `Type`
Now, the main entry point to the `ic-cdk-bindgen` library is `ic_cdk_bindgen::Builder`.
This PR focuses on changing the existing bindgen for inter-canister calls. In the context of Rust CDK, such usage is named `consumer`.
```rs
// build.rs
fn main() {
ic_cdk_bindgen::Builder::new("profile_rs")
.generate_consumer()
.unwrap();
}
```
Then in `lib.rs` of the consumer canister:
```rs
mod profile_rs {
include!(concat!(env!("OUT_DIR"), "/consumer/profile_rs.rs"));
}
use …
```
=> feat!: ic-cdk-bindgen rewrite

examples/profile/src/profile_inter_rs/build.rs, examples/profile/tests/basic.bats, src/ic-cdk-bindgen/src/code_generator.rs, src/ic-cdk-bindgen/src/error.rs, src/ic-cdk-bindgen/src/lib.rs
`Builder::generate_type()` can generate Rust bindings for type only.
Fixes SDK1557
profile example
- ~[ ] I have edited the CHANGELOG accordingly.~
- ~[ ] I have made corresponding changes to the documentation.~
=> feat: generate type only

Cargo.lock, Cargo.toml, e2e-tests/canisters/api_call.rs, e2e-tests/tests/e2e.rs, ic0.txt, src/candid-extractor/CHANGELOG.md, src/candid-extractor/ic_mock.wat, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/mod.rs, src/ic0/Cargo.toml, src/ic0/src/ic0.rs
SDKTG-326
- Bumps `ic0` to v0.23.0 which includes the new system API `in_replicated_execution`.
- Provides safe wrapper of it in `ic-cdk`.
e2e/api-call
=> feat: add API `in_replicated_execution()`

Cargo.lock, Cargo.toml, src/candid-extractor/CHANGELOG.md, src/candid-extractor/Cargo.toml, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml
`ic-cdk` and `ic-cdk-macros` => v0.13.3
`candid-extractor` => v0.1.4
=> chore: release 20240510

e2e-tests/canisters/canister_info.rs, e2e-tests/canisters/management_caller.rs, src/ic-cdk-bindgen/CHANGELOG.md, src/ic-cdk/src/api/management_canister/main/types.rs
Canister settings now include `log_visibility`.
Addresses [feature request on the forum](https://forum.dfinity.org/t/fetching-canister-logs-dynamically-or-by-using-rs-agent/32420/3)
Covered in a test
=> feat: support log_visibility canister setting

src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/src/export.rs
This changes export macros to not contain spaces or brackets, so `cargo build` doesn't give weird errors with GNU ld.
=> fix: ld-compatible symbols

src/ic-cdk-timers/src/lib.rs
=> fix: Use ld-compatible symbol in ic-cdk-timers

README.md, src/ic-cdk/README.md, src/ic-cdk/src/macros.rs
SDK-1803
Clarify that `#[post_upgrade]` should have the same argument type as `#[init]`.
=> docs: clarify post_upgrade argument types

src/ic-cdk/src/api/call.rs
#391 accidentally introduced a memory leak in CallFuture under the right conditions. This reverses it.
=> fix: Fix memory leak in CallFuture

Cargo.lock, Cargo.toml, library/ic-ledger-types/CHANGELOG.md, library/ic-ledger-types/Cargo.toml, src/ic-cdk-macros/CHANGELOG.md, src/ic-cdk-macros/Cargo.toml, src/ic-cdk-timers/CHANGELOG.md, src/ic-cdk-timers/Cargo.toml, src/ic-cdk/CHANGELOG.md, src/ic-cdk/Cargo.toml
This major release adds the support for Canister snapshots which enables data backup and restore.
=> chore: release ic-cdk v0.16.0

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/management_canister/main/types.rs
Canister's `log_visibility` now include `AllowedViewers` variant.
Fixes # (issue): SDK-1799
Regular CI.
=> feat: add AllowedViewers variant to LogVisibility enum

examples/management_canister/src/caller/lib.rs, examples/management_canister/tests/basic.bats, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/management_canister/ecdsa/mod.rs, src/ic-cdk/src/api/management_canister/mod.rs, src/ic-cdk/src/api/management_canister/schnorr/mod.rs, src/ic-cdk/src/api/management_canister/schnorr/types.rs
SDK-1836
Added `schnorr` submodule.
mangement_canister example
=> feat: Add Schnorr signing API

library/ic-ledger-types/CHANGELOG.md, library/ic-ledger-types/src/lib.rs
It is currently not possible to obtain an `AccountIdentifier` as bytes.  It is only possible to obtain hex and then convert the hex back to bytes.  This is resolved by adding an `.as_bytes()` method that returns a reference to the inner bytes.
Fixes #519
A unit test is included that verifies that parsing bytes and returning them as bytes yields the original data.
- Rustdoc is included on the method.
=> feat(ic-ledger-types): Add AccountIdentifier.as_bytes()

ic-cdk-macros/src/export.rs, ic-cdk/CHANGELOG.md, ic-cdk/tests/pass/func_arg_same_name.rs, ic-cdk/tests/pass/method_arg_same_name.rs
SDK-1856
ic-cdk/tests/pass/method_arg_same_name.rs
=> fix: update/query macro could not handle function arguments with the same name as the function itself

.github/workflows/ci.yml, .github/workflows/conventional-commits.yml, .github/workflows/examples.yml, .github/workflows/release-candid-extractor.yml, Cargo.lock, Cargo.toml, e2e-tests/Cargo.toml, e2e-tests/canisters/chunk.rs, e2e-tests/canisters/management_caller.rs, e2e-tests/tests/e2e.rs, library/ic-certified-map/src/rbtree.rs, rust-toolchain.toml, scripts/download_pocket_ic.sh, src/ic-cdk-timers/src/lib.rs, src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/management_canister/main/mod.rs, src/ic-cdk/src/api/management_canister/main/types.rs
SDK-1875
- Support management canister method: `subnet_info`.
- Add types: `SubnetInfoArgs` and `SubnetInfoResult`.
Bumped the MSRV to 1.78.0 which is required by pocket-ic's dependency.
Switched to ubuntu-24.04 runner in CI because recent pocket-ic requires glic that is not available in ubuntu-latest (20.04).
e2e_tests
=> feat: support subnet_info

e2e-tests/src/bin/call_struct.rs, e2e-tests/tests/call_struct.rs, ic-cdk-timers/src/lib.rs, ic-cdk/Cargo.toml, ic-cdk/src/api/call.rs, ic-cdk/src/api/mod.rs, ic-cdk/src/call.rs, ic-cdk/src/lib.rs, ic-cdk/src/prelude.rs
The Call struct API was added to the existing `src/api/call.rs` module.
This PR moves the new API to `src/call.rs` module.
The `src/api/call.rs` is consistent with the main branch with some minor adjustment for the new ic0 crate.
The `src/call.rs` module also got some refreshment.
```Rust
pub type CallResult<R> = Result<R, CallError>;
pub enum CallError {
#[error("Failed to encode the arguments: {0}")]
CandidEncodeFailed(String),
#[error("The IC was not able to enqueue the call with code {0:?}")]
CallPerformFailed(CallPerformErrorCode),
#[error("The call was rejected with code {0:?} and message: {1}")]
CallRejected(RejectCode, String),
#[error("Failed to decode the response as {0}")]
CandidDecodeFailed(String),
}
```
e2e tests
=> feat: root call mod with new CallError

src/ic-cdk/CHANGELOG.md, src/ic-cdk/src/api/management_canister/bitcoin/mod.rs, src/ic-cdk/src/api/management_canister/bitcoin/types.rs
This intentionally calls the deprecated management canister function to be uniform with the rest; they will all be converted as a bloc.
=> feat: Add bitcoin_get_block_headers

e2e-tests/src/bin/async.rs, e2e-tests/tests/async.rs, ic-cdk-timers/src/lib.rs, ic-cdk/src/api/call.rs, ic-cdk/src/call.rs, ic-cdk/src/lib.rs, library/ic-ledger-types/src/lib.rs
The old call API in `ic_cdk::api::call.rs` are deprecated.
`ic-cdk-timers`, `ic-ledger-types` and some e2e tests are migrated to the new `Call::new(...)` API.
During the migration, a bug in `CallPerformErrorCode` handling was found. And both `RejectCode` and `CallPerformErrorCode` are improved to include a `NoError` variant and implemented `Into/From/PartialEq` traits with `u32`.
The e2e tests. And there should be no compiler error/warning across the whole project.
=> chore: deprecate old call API

e2e-tests/src/bin/macros.rs, e2e-tests/tests/macros.rs, ic-cdk-macros/src/export.rs
SDK-1924
* Add `decode_with` hook for customizing arguments decoding.
* When the argument is empty, the macros won't generate the code which get `msg_arg_data` then decode as Candid.
* The callee can send any arguments to such entry-points. And the entry-point won't waste any cycles on decoding it into `'()'`.
* If it's needed, developer can still use `decode_with` to decode the arguments data.
* Some code cleanup for better maintainability.
Added a macros e2e test.
=> feat: macros that decoding arguments can set custom decoder using decode_with

e2e-tests/src/bin/api.rs, e2e-tests/tests/api.rs, ic-cdk/src/api.rs
`msg_deadline ` is a new system API as a part of the Best-Effort Responses feature.
It's specification can be found [here](https://github.com/dfinity/portal/pull/3764).
e2e-tests api.rs
=> feat: safe binding for msg_deadline

ic-cdk-timers/src/lib.rs, ic-cdk/src/call.rs, ic-cdk/src/prelude.rs
There are a few reason we need a redesign of the CallError:
- The previous design made it hard to get the RejectCode which is the most common used field to do error handling.
- There is an initiative to expose error_code in system API. To avoid breaking changes at that time, we start to include error_code now.
Aside from the `CallError`, I introduced `SystemError`. `SystemError` is a variant of `CallError`.
The error type of `call_raw()` and `call_oneway()` is `SystemError`. It implies that the call is rejected by the system.
```rust
pub struct SystemError {
pub reject_code: RejectCode,
pub reject_message: String,
pub error_code: ErrorCode,
pub sync: bool,
}
```
The error type of `call()` and `call_tuple` is `CallError`. They might also failed when decoding the reply.
```rust
pub enum …
```
=> feat: CallError redesign

ic-cdk/src/call.rs
@mraszyk left a few suggestions in #548.
The major change is adding back the `Unrecognized(u32)` variant in `RejectCode`.
The conversion from u32 to `RejectCode` can only fail when the input is 0.
Also I clarified why it is okay to unwrap when args encoding fail. And extract a method to avoid repeating myself.
=> chore: call module followup

Cargo.toml, e2e-tests/src/bin/api.rs, e2e-tests/src/bin/async.rs, e2e-tests/src/bin/call.rs, e2e-tests/src/bin/canister_info.rs, e2e-tests/src/bin/chunk.rs, e2e-tests/src/bin/http_request.rs, e2e-tests/src/bin/management_canister.rs, e2e-tests/tests/call.rs, ic-cdk-timers/src/lib.rs, ic-cdk/src/call.rs, ic-cdk/src/lib.rs, ic-cdk/src/management_canister.rs, ic-cdk/src/prelude.rs, library/ic-ledger-types/src/lib.rs
SDK-1948
Previously, such call retry logic is not possible:
```rust
async fn retry<C: SendableCall>(call_to_retry: C) {
loop {
match call_to_retry.call_raw().await {
// handle
}
}
}
```
Now the implementation is simplified that `CallWith*` structs, `ConfigurableCall` and `SendableCall` traits/impls are removed. As a result, the `prelude` module is removed which was mainly for importing the two `*Call` traits.
The arguments are encoded once in `with_arg` and `with_args`, only the `encoded_args` is saved in the `Call` struct.
Therefore, the call can be sent multiple times.
```rust
async fn retry(call_to_retry: Call<'_, '_>) {
loop {
match call_to_retry.call_raw().await {
// handle
}
}
}
```
> This PR relies on https://github.com/dfinity/candid/pull/593.
> We need to wait for a Candid …
=> feat: simplify Call implementation and enable retry logic

e2e-tests/Cargo.toml, e2e-tests/src/bin/api.rs, e2e-tests/src/bin/async.rs, e2e-tests/src/bin/call.rs, e2e-tests/tests/call.rs, ic-cdk-timers/src/lib.rs, ic-cdk/src/api/call.rs, ic-cdk/src/call.rs, ic-cdk/src/management_canister.rs, ic-response-codes/src/lib.rs, library/ic-ledger-types/src/lib.rs
SDK-1950
For maintainable better user experience, this PR made some fundamental changes to the inter-canister call API (`call.rs`).
Replaced `Call::new()` with `Call::bounded_wait()` and `Call::unbounded_wait()`.
- `impl IntoFuture for Call`. So that a `Call` can be `.await` directly instead of invoking the `call*` method. No awkward `Call::new().call()` syntax.
- Replaced the oneway execution with the shorter and clearer `Call::oneway()` method.
- After a `Call` is executed by `await` , a `candid()`/`candid_tuple()` method can be chained to decode the response.
- `Error`: The top-level error type encapsulating all possible errors.
- `CallFailed`: Errors related to the execution of the call itself.
- `CallRejected`: Errors when an inter-canister call is rejected.
- `CallPerformFailed`: …
=> feat: finalize call api

e2e-tests/src/bin/canister_info.rs, e2e-tests/src/bin/chunk.rs, e2e-tests/src/bin/http_request.rs, e2e-tests/src/bin/management_canister.rs, ic-cdk/src/management_canister.rs, ic-management-canister-types/CHANGELOG.md, ic-management-canister-types/src/lib.rs
Renamed:
- `create_canister` -> `create_canister_with_cycles`
- `sign_with_ecdsa` -> `sign_with_ecdsa_with_cycles`
- `sign_with_schnorr` -> `sign_with_schnorr_with_cycles`
- `http_request` -> `http_request_with_cycles`
- `http_request_with_closure` -> `http_request_with_closure_with_cycles`
It is intended to make the method names longer. Because we will soon have the [System API to calculate cycle cost](https://github.com/dfinity/portal/pull/4110) for these management canister API. Once it is available, we can provide the methods without the postfix which handle the cycle cost calculation under the hood.
Also did a minor doc fix in `ic-management-canister-types`.
e2e
=> feat: add _with_cycles postfix to management canister methods that require cycles

.github/workflows/ci.yml, Cargo.toml, ic-cdk/src/api/stable/mod.rs, ic-cdk/src/call.rs, ic-cdk/src/stable.rs, library/ic-certified-map/src/rbtree.rs, rust-toolchain.toml
The MSRV is downgraded to 1.75.0 which is the same as v0.17.0.
I upgraded the MSRV 3 months ago just because some indirect dependencies introduced by `pocket-ic` in `e2e-tests` requires Rust v1.78.0.
- Set `channel = "stable"` in `rust-toolchain.toml` so that we always use the latest stable toolchain for development.
- Will have the latest `clippy` ruleset for better code quality
- No need to deal with MSRV issue in `e2e-tests` dependencies (e.g. this [comment](https://github.com/dfinity/cdk-rs/pull/563#issuecomment-2689242196)).
- Changed the `build` job in `ci.yml` to `msrv` which ensures `cargo build` with MSRV.
CI
=> chore: MSRV back to 1.75.0

ic-management-canister-types/CHANGELOG.md, ic-management-canister-types/Cargo.toml, ic-management-canister-types/src/lib.rs, ic-management-canister-types/tests/candid_equality.rs, ic-management-canister-types/tests/ic.did
The specification mentions these types, but they are not in the ic-management-canister-types yet. 
The new type was added to the candid_equality.rs test
=> feat: Add types for fetching canister logs

e2e-tests/Cargo.toml, e2e-tests/src/bin/macros.rs, e2e-tests/tests/macros.rs, ic-cdk-macros/src/export.rs, ic-cdk/CHANGELOG.md, ic-cdk/src/macros.rs, ic-management-canister-types/Cargo.toml, ic-management-canister-types/tests/candid_equality.rs
Requested and inspired by the `OpenChat` [fork](https://github.com/hpeebles/cdk-rs/commit/19f04d7d996d77b1c2f938e4c7e1efd8e3f12910).
- Enabled `update`/`query` macros to set custom result encoder via `encode_with`.
- The encoder function should takes the same type of the result and returns a `Vec<u8>`.
- For consistency, the custom argument decoder is also changed to take a `Vec<u8>` as an argument. No need to call `msg_arg_data()`.
- Added explanation of `decode_with`/`encode_with` in macros documentation.
e2e-tests - macros.rs
=> feat: update/query can set custom result encoder

ic-cdk-timers/src/lib.rs
Set the executor context when invoking functions via canister timers .
The OpenChat tests were all failing before this change with an error saying the following -
```
[ic-cdk-timers] canister_global_timer: CallRejected(CallRejected { reject_code: CanisterError, reject_message: "IC0503: Error from Canister txyno-ch777-77776-aaaaq-cai: Canister called `ic0.trap` with message: 'Panicked at '`spawn` can only be called from an executor context'
```
With this change applied, the tests all pass.
=> fix: set the executor context when invoking functions via canister timers 

ic-cdk/src/call.rs, ic-cdk/src/management_canister.rs
To be merged or cherry-picked into https://github.com/dfinity/cdk-rs/pull/570
=> feat: Add higher level cost APIs 

e2e-tests/src/bin/api.rs, e2e-tests/tests/api.rs, ic-cdk/src/api.rs, ic0/ic0.txt, ic0/src/ic0.rs
=> feat: subnet_self in ic0 and api

Cargo.toml, e2e-tests/src/bin/canister_info.rs, e2e-tests/src/bin/management_canister.rs, ic-management-canister-types/CHANGELOG.md, ic-management-canister-types/Cargo.toml, ic-management-canister-types/src/lib.rs, ic-management-canister-types/tests/ic.did
SDK-2025
- wasm_memory_threshold in canister_settting: https://github.com/dfinity/portal/pull/3761 
- memory_metrics in canister_status: https://github.com/dfinity/portal/pull/5240 
Candid equality test with the updated `ic.did`.
=> feat!: update management types

Cargo.toml, e2e-tests/Cargo.toml, e2e-tests/src/bin/api.rs, e2e-tests/src/bin/bitcoin_canister.rs, e2e-tests/src/bin/call.rs, e2e-tests/tests/api.rs, e2e-tests/tests/call.rs, e2e-tests/tests/test_utilities.rs, ic-cdk-timers/src/lib.rs, ic-cdk/src/api.rs, ic-cdk/src/call.rs, ic0/Cargo.toml, ic0/ic0.txt, ic0/src/ic0.rs
SDK-2024
- Added new system API: `ic0. canister_liquid_cycle_balance` in `ic0`.
- Added safe binding in `api.rs`.
- Utilized this method to check if cycle balance is sufficient to call before `ic0.perform`.
- Added a new error type (`InsufficientLiquidCycleBalance`).
- Restructured the error types to be flatter.
e2e with updated `pocket-ic`.
=> feat: canister_liquid_cycle_balance

Cargo.toml, ic-cdk-macros/Cargo.toml, ic-cdk-timers/Cargo.toml, ic-cdk/CHANGELOG.md, ic-cdk/Cargo.toml, ic-cdk/V18_GUIDE.md, ic-cdk/src/api.rs, ic-cdk/src/api/management_canister/mod.rs, library/ic-ledger-types/Cargo.toml
SDK-2017
- properly deprecate api/ submodules and items there
- The modules should not be hidden. Users should still be able to see the deprecated API and check the notes of replacement.
- update changelog to emphasize changes since alpha.1
- update V18_GUIDE.md
CI
=> chore: release v0.18.0-alpha.2

.github/workflows/ci.yml, e2e-tests/Cargo.toml, e2e-tests/src/bin/management_canister.rs, e2e-tests/tests/test_utilities.rs, scripts/download_pocket_ic_server.sh
Since https://github.com/dfinity/cdk-rs/pull/568, the pocket-ic server binary is cached during the e2e tests.
It is hard to implement correctly. https://github.com/dfinity/cdk-rs/pull/584 fixed the flaky cases but failed to handle [tag updates](https://github.com/dfinity/cdk-rs/actions/runs/14249470133/job/39938524676#step:7:194).
This PR brings back the shell script which downloads the pocket-ic server. In e2e tests, a utility function still checks the tag and inform to run the shell script if tag mismatch or the server binary doesn't exist.
* Updated the pocket-ic tag to `release-2025-04-03_03-15-base`.
* The `freezing_threshold` is enforced to be at least 604800 seconds. So the test code is adjusted.
* Replaces the GitHub action `arduino/setup-protoc@v3` with the native package manager …
=> ci: fix pocket-ic server download

Cargo.toml, e2e-tests/Cargo.toml, e2e-tests/tests/test_utilities.rs, ic-cdk-macros/Cargo.toml, ic-cdk-timers/CHANGELOG.md, ic-cdk-timers/Cargo.toml, ic-cdk/CHANGELOG.md, ic-cdk/Cargo.toml, ic-cdk/V18_GUIDE.md, ic0/Cargo.toml, library/ic-ledger-types/CHANGELOG.md, library/ic-ledger-types/Cargo.toml
SDK-2086
Cut the stable v0.18.0 release as the "Bounded-Wait Calls" feature is enabled on all the mainnet subnets.
CI
=> chore: release v0.18.0

ic-cdk/V18_GUIDE.md
I was reading the [V18 migration guide](https://github.com/dfinity/cdk-rs/blob/main/ic-cdk/V18_GUIDE.md), and since I had no idea what "Bounded vs Unbounded calls" were, I ended up spending some time searching for resources that explain the difference. Even use the AI on the portal. That’s why, even though links to the portal often end up broken at some point, I think in this case it’s useful to include a link to the documentation.
- Link term "Bounded-Wait Calls" to https://internetcomputer.org/docs/references/async-code#ic-call-types
=> docs: provide a link to bounded doc in V18 migration guide

e2e-tests/src/bin/macros/main.rs, e2e-tests/tests/macros.rs, ic-cdk-macros/src/export.rs
SDK-2110
The macros attributes `guard`, `decode_with` and `encode_with` accept function names. They were restricted to take `syn::Ident` only.
This PR extended the attributes to take `syn::Path` instead which allows:
- Functions defined in other modules: `other_mod::guard`;
- Functions with generic parameters: `candid_decode_with_quota::<1000,_>`;
Added e2e tests.
=> feat: macros attrs can take a Path

e2e-tests/src/bin/call.rs, ic-cdk/CHANGELOG.md, ic-cdk/src/call.rs
SDK-2129
The existing `Call::with_raw_args` method takes a reference of the bytes which may prevent storing the call in collections or returning it from functions if the arguments don't live long enough.
This PR added another method which takes the ownership of the bytes.
Added in e2e tests.
=> feat: add Call::take_raw_args which owns the bytes

Cargo.lock, Cargo.toml, src/ic-cdk-executor/Cargo.toml, src/ic-cdk-executor/build.rs, src/ic-cdk-executor/src/lib.rs, src/ic-cdk/Cargo.toml, src/ic-cdk/src/api/call.rs, src/ic-cdk/src/lib.rs
This PR targets a feature branch because it is for ic-cdk@0.17, not 0.18.
=> chore: Factor out v2 executor into separate crate

Cargo.lock, src/ic-cdk-macros/Cargo.toml, src/ic-cdk/Cargo.toml
Includes publishing new crate `ic-cdk-executor`.
=> chore: Release 0.17.2

Cargo.toml, ic-cdk-executor/Cargo.toml
The ic-cdk release is deferred for now.
=> chore: Release ic-cdk-executor v1.0.0

ic-cdk/src/bitcoin_canister.rs
Update bitcoin `regtest` configuration to be same as the bitcoin `mainnet`.
```
fees = record {
get_current_fee_percentiles = 10_000_000 : nat;
get_utxos_maximum = 10_000_000_000 : nat;
get_block_headers_cycles_per_ten_instructions = 10 : nat;
get_current_fee_percentiles_maximum = 100_000_000 : nat;
send_transaction_per_byte = 20_000_000 : nat;
get_balance = 10_000_000 : nat;
get_utxos_cycles_per_ten_instructions = 10 : nat;
get_block_headers_base = 50_000_000 : nat;
get_utxos_base = 50_000_000 : nat;
get_balance_maximum = 100_000_000 : nat;
send_transaction_base = 5_000_000_000 : nat;
get_block_headers_maximum = 10_000_000_000 : nat;
};
```
You can get the fees by `get_config` API on the [BTC Mainnet Canister](https://dashboard.internetcomputer.org/canister/ghsi2-tqaaa-aaaan-aaaca-cai) …
=> chore: update bitcoin regtest configuration to be same as the bitcoin mainnet.

e2e-tests/Cargo.toml, ic-cdk/V18_GUIDE.md, ic-cdk/src/lib.rs
This adds a deprecated `spawn` function where it was removed from in 0.17, which works like the old one most of the time but panics in complicated cases. To be replaced with a perfect solution in 0.19.
=> fix: Add `spawn` order compatibility adapter

ic-cdk-executor/src/lib.rs
This check was an artefact of tasks being canceled by the last handle to die instead of the first.
=> fix: Fix cancelled tasks registered as trapped

Cargo.toml, ic-cdk-macros/Cargo.toml, ic-cdk-timers/CHANGELOG.md, ic-cdk-timers/Cargo.toml, ic-cdk/CHANGELOG.md, ic-cdk/Cargo.toml, ic0/CHANGELOG.md, ic0/Cargo.toml
Note that major ic0 updates are not major updates to ic-cdk-timers.
=> chore: Release ic-cdk@0.18.5, ic0@1.0.0, ic-cdk-timers@0.12.2

Cargo.toml, ic-management-canister-types/CHANGELOG.md, ic-management-canister-types/Cargo.toml, ic-management-canister-types/src/lib.rs, ic-management-canister-types/tests/candid_equality.rs, ic-management-canister-types/tests/ic.did
Follow-up pr to https://github.com/dfinity/cdk-rs/pull/639. 
Moved the canister snapshot related types from ic-utils to ic-management-canister-types, please refer to [PR](https://github.com/dfinity/agent-rs/pull/654) on the agent-rs side.
[SDK-2237](https://dfinity.atlassian.net/browse/SDK-2237)
Extended the candid_equality test to cover the new methods and types.
[SDK-2237]: https://dfinity.atlassian.net/browse/SDK-2237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added types for canister snapshot download/upload.

ic-cdk-bindgen/src/code_generator.rs
`cargo clippy` has a new lint: "warning hiding a lifetime that's elided elsewhere is confusing" since Rust 1.89.0.
This PR resolves the new [warnings](https://github.com/dfinity/cdk-rs/actions/runs/16927306871/job/47965543006).
CI
=> fix(clippy): Update lifetimes to satisfy new lints

Cargo.toml, e2e-tests/src/bin/macros/main.rs, e2e-tests/tests/macros.rs, ic-cdk-macros/src/export.rs, ic-cdk/CHANGELOG.md
The `skipping_quota` macro option was removed in `ic-cdk` v0.18.
A default 10_000 `skipping_quota` was set in the macros. See [here](https://github.com/dfinity/cdk-rs/commit/bbd63393f40c5af4abbfbcc4592c39735a168e8f#diff-512c30fae8883899d66bca2b49ddc68da3a167d3329eabad931e7603ed2269f3R65-R68).
Canisters migrating from v0.17 to v0.18 would silently lost the protection against DoS attack.
This PR brings back the default `skipping_quota`. 
There should be no public `ic-cdk` API that directly exposes configuration of  `skipping_quota` or `DecoderConfig`.
Users will need to use `#[update(decode_with = "...")]` if they need any customized decoding.
Added `default_skipping_quota` in the `macros` e2e test.
=> feat: set default skipping quota

Cargo.toml, ic-cdk/CHANGELOG.md, ic-management-canister-types/CHANGELOG.md, ic-management-canister-types/Cargo.toml
We now release `ic-management-canister-types` v0.4.0 so that downstream projects can start supporting the IC environment variables.
`ic-cdk` is NOT released together in this PR.
=> chore: release ic-management-canister-types v0.4.0

Cargo.toml, ic-management-canister-types/CHANGELOG.md, ic-management-canister-types/Cargo.toml, ic-management-canister-types/src/lib.rs, ic-management-canister-types/tests/ic.did
SDK-2307
- Added the `source` field in `LoadSnapshotRecord`.
- The `TakenFromCanister` and `MetadataUpload` variants in `SnapshotSource` have been updated to use `candid:Reserved` in [this pr](https://github.com/dfinity/ic/pull/6163).
- Followed up on the renaming from `main_memory` to `wasm_memory` in [this pr](https://github.com/dfinity/ic/pull/6420).
- Updated candid to `0.10.18`.
- Bumped `ic-management-canister-types` to `0.4.1`.
Updated the `ic.did` for `candid_equality_test`.
=> fix: updated `SnapshotSource` and release ic-management-canister-types 0.4.1

.github/workflows/ci.yml, e2e-tests/build.rs, e2e-tests/src/bin/bindgen_callee/management.toml, ic-cdk-bindgen/README.md, ic-cdk-bindgen/src/lib.rs
SDK-2322
Use "type selector" config to customize how Candid types are translated to Rust types.
Added `management.toml` for the management canister bindgen in e2e.
=> feat(bindgen): set type selector config

e2e-tests/src/bin/macros/main.rs
Fix new clippy errors as in this [CI failure](https://github.com/dfinity/cdk-rs/actions/runs/17888753904/job/50866394641#step:6:740).
=> fix: address Rust 1.90.0 clippy lints

ic-cdk/Cargo.toml, ic-cdk/src/api.rs, ic-cdk/src/call.rs, ic-cdk/src/management_canister.rs
This PR clarifies the documentation for the `Call` type and includes several minor fixes for accuracy and readability.
The **primary update** addresses a source of confusion: the `Call` struct is **not a `Future`** itself. The documentation now clearly instructs users to call **`.into_future()`** to obtain the awaitable `CallFuture` object.
---
* **`http_request`**: Removed the outdated reference to "user-specified amount of cycles" which was incorrectly copied from a deprecated API.
* **`canister_status`**: Cleaned up the documentation to fix an issue where extra periods (`.`) in the list caused incorrect markdown rendering.
=> docs: Clarify Call to CallFuture conversion and fix minor inaccuracies
