.github/workflows/examples.yml
examples/asset_storage/tests/basic.bats
examples/counter/tests/basic.bats
src/ic-cdk/src/api.rs
src/ic-cdk/src/api/call.rs
src/ic-cdk/src/api/ic0.rs

Especially renaming the funds related APIs to cycles.
Fixes https://github.com/dfinity/cdk-rs/issues/38

feat: Update to ic-ref-0.14

---

Cargo.toml
src/ic-certified-map/Cargo.toml
src/ic-certified-map/src/LICENSE
src/ic-certified-map/src/README.md
src/ic-certified-map/src/hashtree.rs
src/ic-certified-map/src/hashtree/test.rs
src/ic-certified-map/src/lib.rs
src/ic-certified-map/src/rbtree.rs
src/ic-certified-map/src/rbtree/debug_alloc.rs
src/ic-certified-map/src/rbtree/test.rs

This change introduces a new package providing a merkleized map data
structure that can be used by canister authors to implement certified
queries.

feat: add ic-certified-map package

---

examples/chess/dfx.json
examples/counter/dfx.json
examples/counter/src/counter_rs/lib.rs
examples/print/dfx.json
examples/profile/dfx.json
examples/profile/src/profile_inter_rs/lib.rs
examples/profile/src/profile_rs/lib.rs

The only exception is the frontend part of "chess" (chess_rs_assets). We may fix it in another PR.

fix: all examples work with latest dfx 0.8.1

---

src/ic-certified-map/CHANGELOG.md
src/ic-certified-map/Cargo.toml

Also the Changelog has been fixed.
Close #176

chore: release ic-certified-map v0.3.0

---

Cargo.toml
src/ic-certified-assets/Cargo.toml
src/ic-certified-assets/LICENSE
src/ic-certified-assets/README.md
src/ic-certified-assets/src/lib.rs
src/ic-certified-assets/src/rc_bytes.rs

Signed-off-by: John Plevyak <jplevyak@gmail.com>

feat: Add ic-certified-assets crate for serving certified assets from Rust canisters.

---

src/ic-certified-assets/README.md

Signed-off-by: John Plevyak <jplevyak@gmail.com>

chore: Update ic-certified-assets README.

---

src/ic-cdk/src/api/stable.rs

fix: Remove out-of-bounds vulnerability

---

src/ic-cdk-optimizer/Cargo.toml
src/ic-cdk-optimizer/src/main.rs
src/ic-cdk-optimizer/src/passes.rs
src/ic-cdk-optimizer/src/passes/binaryen.rs

chore: Update clap to 3.1

---

src/ic-cdk-macros/Cargo.toml
src/ic-cdk-optimizer/Cargo.toml
src/ic-cdk/Cargo.toml
src/ic-certified-assets/Cargo.toml
src/ic-certified-map/Cargo.toml
src/ic-ledger-types/Cargo.toml

Add `repository` field to all manifests, and update `categories` fields to be more meaningful.

chore: Update manifest metadata

---

README.md
docs/modules/rust-guide/pages/rust-profile.adoc
docs/modules/rust-guide/pages/rust-quickstart.adoc
examples/asset_storage/src/asset_storage_rs/Cargo.toml
examples/chess/src/chess_rs/Cargo.toml
examples/counter/src/counter_rs/Cargo.toml
examples/counter/src/inter2_rs/Cargo.toml
examples/counter/src/inter_rs/Cargo.toml
examples/print/src/print_rs/Cargo.toml
examples/profile/src/profile_inter_rs/Cargo.toml
examples/profile/src/profile_rs/Cargo.toml
src/ic-cdk-macros/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml
src/ic-certified-assets/Cargo.toml
src/ic-ledger-types/Cargo.toml

Prepare for releasing `ic-cdk` and `ic-cdk-macro` v0.5.0.

chore: release cdk 0.5.0

---

src/ic-cdk/src/api/stable.rs

This reverts commit 8a2843f82460c19a730c08666ef2c5f474a931b2.
I am working on a better solution for writing to stable memory which buffers the writes, reducing calls to grow stable memory. So reverting these original changes for now.
Also, this change was calling `stable_size` too frequently rather than using the `capacity` field of `StableWriter`.
My next version will not have this issue.
This simply reverts back to how the code originally was so no testing needed.

revert: "feat: Add `grow_then_write_stable_bytes` helper method (#240)"

---

src/ic-certified-assets/Cargo.toml

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

chore: ic-certified-assets v0.2.2

---

src/ic-ledger-types/CHANGELOG.md
src/ic-ledger-types/Cargo.toml

chore: release ic-ledger-types v0.1.2

---

README.md
e2e-tests/Cargo.toml
examples/chess/src/chess_rs/Cargo.toml
examples/counter/src/counter_rs/Cargo.toml
examples/counter/src/inter2_rs/Cargo.toml
examples/counter/src/inter_rs/Cargo.toml
examples/profile/src/profile_inter_rs/Cargo.toml
examples/profile/src/profile_rs/Cargo.toml
src/ic-cdk-macros/Cargo.toml
src/ic-cdk/Cargo.toml
src/ic-certified-assets/Cargo.toml
src/ic-ledger-types/Cargo.toml

chore: Upgrade candid to v0.7.15

---

src/ic-cdk-macros/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml

chore: release ic-cdk v0.5.3

---

src/ic-cdk-macros/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml

chore: release ic-cdk v0.5.4

---

src/ic-cdk-macros/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml
src/ic-cdk/src/api/call.rs

For RejectionCode to be used, we also need to implement `Deserialize`

feat: Derive Deserialize for RejectionCode

---

Cargo.toml
examples/asset_storage/Cargo.toml
examples/chess/Cargo.toml
examples/counter/Cargo.toml
examples/management_canister/Cargo.toml
examples/print/Cargo.toml
examples/profile/Cargo.toml

candid has new release including the feature from the patch before.
CI

chore: remove patch for candid

---

src/ic-cdk-macros/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml

chore: release cdk v0.5.6

---

src/ic-certified-assets/CHANGELOG.md
src/ic-certified-assets/Cargo.toml

Changelog:
- https://github.com/dfinity/cdk-rs/pull/305
Fixes [SDK-678](https://dfinity.atlassian.net/browse/SDK-678)
unit tests

chore: release `ic-certified-assets` `0.2.5`

---

src/ic-cdk-macros/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml

chore: release ic-cdk v0.5.7

---

README.md
e2e-tests/Cargo.toml
e2e-tests/canisters/async.rs
e2e-tests/tests/e2e.rs
examples/asset_storage/src/asset_storage_rs/Cargo.toml
examples/chess/src/chess_rs/Cargo.toml
examples/counter/src/counter_rs/Cargo.toml
examples/counter/src/inter2_rs/Cargo.toml
examples/counter/src/inter_rs/Cargo.toml
examples/management_canister/src/caller/Cargo.toml
examples/print/src/print_rs/Cargo.toml
examples/profile/src/profile_inter_rs/Cargo.toml
examples/profile/src/profile_rs/Cargo.toml
library/ic-ledger-types/Cargo.toml
src/ic-cdk-macros/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml
src/ic-cdk/src/api/call.rs
src/ic-cdk/src/api/mod.rs
src/ic-cdk/src/lib.rs

feat: upgrade candid to 0.8.0

---

library/ic-ledger-types/CHANGELOG.md
library/ic-ledger-types/Cargo.toml

chore: release ic-ledger-types v0.2.0

---

e2e-tests/canisters/timers.rs
e2e-tests/tests/e2e.rs
src/ic-cdk/src/timer.rs

The timers should be able to cancel themselves.
Fixes RUN-515

fix: RUN-515: Allow timers to cancel themselves

---

library/ic-ledger-types/CHANGELOG.md
library/ic-ledger-types/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml

chore: release ic-cdk v0.6.10 and ic-ledger-types v0.2.1

---

library/ic-ledger-types/Cargo.toml
src/ic-cdk-timers/Cargo.toml
src/ic-cdk-timers/README.md
src/ic-cdk-timers/src/lib.rs

Fix two issues in #369 which blocks actual publish on crates.io

chore: release continue

---

library/ic-certified-map/CHANGELOG.md
library/ic-certified-map/Cargo.toml
library/ic-ledger-types/CHANGELOG.md
library/ic-ledger-types/Cargo.toml
src/ic-cdk-macros/CHANGELOG.md
src/ic-cdk-macros/Cargo.toml
src/ic-cdk-timers/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml

chore: release crates

---

examples/management_canister/src/caller/lib.rs
src/ic-cdk/CHANGELOG.md
src/ic-cdk/src/api/management_canister/http_request.rs
src/ic0/src/lib.rs

Fixes SDK-1042
examples/management_canister

feat: http_request_with_cycles

---

src/ic-cdk/CHANGELOG.md
src/ic-cdk/src/api/mod.rs
src/ic0/ic0.txt
src/ic0/src/ic0.rs

Introduces new system API call `ic0.is_controller`as described in this [spec change](https://github.com/dfinity/interface-spec/pull/141).
Fixes [SDK-1059](https://dfinity.atlassian.net/browse/SDK-1059)

feat: add ic0.is_controller to ic0 and cdk-rs

---

README.md
library/ic-certified-map/CHANGELOG.md
library/ic-ledger-types/CHANGELOG.md
src/ic-cdk-bindgen/CHANGELOG.md
src/ic-cdk-timers/CHANGELOG.md
src/ic-cdk-timers/README.md
src/ic-cdk/CHANGELOG.md

chore: release ic-cdk v0.10.0 and other crates

---

.github/workflows/conventional-commits.yml
.github/workflows/examples.yml

Only "ci" and "examples" should be scheduled twice a week.

test: fix CI schedule

---

examples/print/Cargo.toml
examples/print/src/print_rs/Cargo.toml
examples/print/src/print_rs/lib.rs
examples/print/tests/basic.bats

This PR adds the missing bats test and fix the broken example.

test: fix print example

---

Cargo.lock
Cargo.toml
src/ic-cdk-timers/CHANGELOG.md
src/ic-cdk-timers/Cargo.toml

chore: release ic-cdk-timers v0.7.0

---

Cargo.lock
Cargo.toml
library/ic-ledger-types/CHANGELOG.md
library/ic-ledger-types/Cargo.toml
src/ic-cdk-macros/Cargo.toml
src/ic-cdk-timers/CHANGELOG.md
src/ic-cdk-timers/Cargo.toml
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml

Fixes the breaking change from 0.13.3

chore: Release 0.14.0

---

Cargo.lock
Cargo.toml
README.md
library/ic-ledger-types/CHANGELOG.md
library/ic-ledger-types/Cargo.toml
src/ic-cdk-macros/Cargo.toml
src/ic-cdk-timers/CHANGELOG.md
src/ic-cdk-timers/Cargo.toml
src/ic-cdk-timers/README.md
src/ic-cdk/CHANGELOG.md
src/ic-cdk/Cargo.toml
src/ic-cdk/README.md

chore: release 0.15.0

---

Cargo.toml
README.md
ic-cdk-macros/README.md
ic-cdk/CHANGELOG.md
ic-cdk/README.md
ic-cdk/V18_GUIDE.md
ic-cdk/src/bitcoin_canister.rs
ic-cdk/src/lib.rs
ic-cdk/src/management_canister.rs
ic-response-codes/Cargo.toml

Added `V18_GUIDE.md`.
Updated `CHANGELOG.md`.
Also did some minor improvements / cleanup.

docs: version guide for v0.18

---

ic-cdk/src/management_canister.rs

SDK-2020
- Selected the appropriate type of bounded/unbounded wait call for each method based on the characteristics of the endpoint.
- Improve the module documentation.
CI

feat: select (un)bounded_wait for management functions

---

ic-cdk/src/call.rs

feat: add a public Constructor for CallRejected

---

ic-cdk/CHANGELOG.md

Update changelog for https://github.com/dfinity/cdk-rs/pull/612
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

chore: update changelog.
